import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

// Build-time data loader: inlines public/stats.json into the homepage bundle
// so the rendered HTML contains real counts (SEO + zero-flash render).
// The file is regenerated by `node generate.js` before any vitepress build.
export default {
  watch: resolve(__dirname, "../public/stats.json"),
  async load() {
    const statsPath = resolve(__dirname, "../public/stats.json");
    const raw = await readFile(statsPath, "utf8");
    return JSON.parse(raw);
  },
};
