name: metanorma

on:
  push:
    branches: [ master, v2, v3 ]
  pull_request:

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  test:
    name: Test on Ruby ${{ matrix.ruby.version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    needs: prepare
    if: needs.prepare.outputs.push-for-tag != 'true'

    continue-on-error: ${{ matrix.ruby.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: metanorma/metanorma

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "formulas"

      - run: |
          mkdir $HOME/.fontist
          mv formulas $HOME/.fontist/formulas
        shell: bash

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
          rubygems: ${{ matrix.ruby.rubygems }}
          bundler-cache: true

      - uses: metanorma/ci/change-tmpdir-action@main
        with:
          tmpdir: ${{ github.workspace }}/tmp

      - run: bundle exec rake
