name: metanorma

on:
  push:
    branches: [ master, v2, v3, v4 ]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/links.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/links.yml'

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  test:
    name: Test on Ruby ${{ matrix.ruby.version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    needs: prepare
    if: needs.prepare.outputs.push-for-tag != 'true'

    continue-on-error: ${{ matrix.ruby.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: metanorma/metanorma

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: "formulas"

      - run: |
          mkdir -p $HOME/.fontist/versions/v4
          mv formulas $HOME/.fontist/versions/v4/formulas
        shell: bash

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
          rubygems: ${{ matrix.ruby.rubygems }}
          bundler-cache: true

      - uses: metanorma/ci/fontist-repo-setup@main
        with:
          private-fonts-pat: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          use-bundler: 'true'

      - uses: metanorma/ci/inkscape-setup-action@main

      - run: bundle exec rake
