name: test

on:
  push:
    branches: [ 'v[0-9]+' ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3

      - uses: tj-actions/changed-files@v35
        id: files
        with:
          json: true

      - run: |
          echo "${{ steps.files.outputs.all_changed_files }}" > changed.json
        shell: bash

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - if: matrix.os == 'ubuntu-latest'
        run: bundle exec ruby test/test_formulas.rb --every-platform --platform linux

      - if: matrix.os == 'macos-latest'
        run: bundle exec ruby test/test_formulas.rb --platform macos

      - if: matrix.os == 'windows-latest'
        run: bundle exec ruby test/test_formulas.rb --platform windows
